version: '3.8'

services:
  app:
    build: .
    ports:
      - '3001:3000' # Change the host port to 3001
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - db

  db:
    image: 'nouchka/sqlite3'
    volumes:
      - ./database.sqlite:/data/database.sqlite
